name: Post File to Endpoint

on:
  push:
    paths:
      - 'models/**'

jobs:
  post_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed folders
        id: changed_folders
        run: |
          changed_folders=$(git diff --name-only HEAD~1 HEAD | xargs -n 1 dirname | sort -u | grep 'models' | awk -F"/" '{print $2}' | uniq | tr '\n' ',')
          echo "changed_folders=${changed_folders%,}" >> $GITHUB_ENV
      
      - name: Print changed_folders
        run: |
          echo "Changed folders: ${{ env.changed_folders }}"

      - name: Compress action step
        run: |
          IFS=',' read -r -a folders <<< "${{ env.changed_folders }}"
          for folder in "${folders[@]}"; do
            if [ -n "$folder" ]; then
              tar -czvf "$folder.tar.gz" "models/$folder"
            fi
          done
      
      - name: List files
        run: ls -l

      - name: Post files to endpoint
        run: |
          IFS=',' read -r -a folders <<< "${{ env.changed_folders }}"
          files=()
          for folder in "${folders[@]}"; do
            if [ -n "$folder" ]; then
              files+=(-F "file=@$folder.tar.gz")
            fi
          done
          curl -X POST -H "Content-Type: multipart/form-data" "${files[@]}" https://us-central1-buggy-174216.cloudfunctions.net/accept_tar_req

      # - name: Post file to endpoint
      #   run: |
      #     IFS=',' read -r -a folders <<< "${{ env.changed_folders }}"
      #     for folder in "${folders[@]}"; do
      #       base_folder=$(echo "$folder" | awk -F"/" '{print $2}')
      #       curl -X POST \
      #       -H "Content-Type: multipart/form-data" \
      #       -F "file=@$base_folder.tar.gz" \
      #       https://us-central1-buggy-174216.cloudfunctions.net/accept_tar_req
      #     done
