name: Post File to Endpoint

on:
  push:
    paths:
      - 'models/**'

jobs:
  post_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List changed folders
        id: changed_folders
        run: |
          changed_folders=$(git diff --name-only HEAD~1 | xargs -n 1 dirname | uniq | grep './models/')
          echo "::set-output name=folders::$changed_folders"
      
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.3
        id: compress
        with:
          command: c
          cwd: ./
          files: |
            ./models/sample_model
          outPath: sample_model.tar.gz

      - name: List files
        run: ls -l

      - name: Post file to endpoint
        run: |
          curl -v -X POST \
          -H "Content-Type: multipart/form-data" \
          -F "file=@sample_model.tar.gz" \
          https://us-central1-buggy-174216.cloudfunctions.net/accept_tar_req
