name: Post File to Endpoint

on:
  push:
    paths:
      - 'models/**'

jobs:
  post_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed folders
        id: changed_folders
        run: |
          changed_folders=$(git diff --name-only HEAD^ HEAD | xargs -n 1 dirname | sort -u | grep 'models/')
          echo "changed_folders=$changed_folders" >> $GITHUB_ENV

      - name: Compress action step
        run: |
          IFS=$'\n' read -d '' -r -a folders <<< "$changed_folders"
          for folder in "${folders[@]}"; do
            base_folder=$(echo "$folder" | awk -F"/" '{print $2}')
            tar -czvf "$base_folder.tar.gz" "$folder"
          done

      - name: Post file to endpoint
        run: |
          IFS=$'\n' read -d '' -r -a folders <<< "$changed_folders"
          for folder in "${folders[@]}"; do
            base_folder=$(echo "$folder" | awk -F"/" '{print $2}')
            curl -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "file=@$base_folder.tar.gz" \
            https://us-central1-buggy-174216.cloudfunctions.net/accept_tar_req
          done
